### ISSUE TITLE
How to install using Portainer?

### ISSUE THREAD

**Issue by BobWs** [Crusader99/standardnote-server#2]
Hi,
How can I install your repo using portainer? I can’t find this image on docker-hub. And GitHub isn’t supported within portainer.
TIA

**Comment by Crusader99** [comment]
This image can now be found on Docker-Hub: https://hub.docker.com/r/crusaders/standardnote-server

**Comment by BobWs** [comment]
Does files work with your image?

**Comment by Crusader99** [comment]
It's implemented, but I can't recommend using it yet because of possible conflicts with files between multiple users. Current status: https://github.com/mdouchement/standardfile/pull/93
